
spring:
  application:
    name: bff-service


  grpc:
    client:
      channels:
        product_service:
          address: ${PRODUCT_SERVICE_ADDRESS:localhost:9091}
          negotiation-type: PLAINTEXT
        category_service:
          address: ${CATEGORY_SERVICE_ADDRESS:localhost:9092}
          negotiation-type: PLAINTEXT
    server:
      port: ${GRPC_PORT:9093}

server:
  port: ${SERVER_PORT:8081}