
spring:
  application:
    name: bff-service


  grpc:
    client:
      channels:
        product-service:
          address: ${PRODUCT_SERVICE_ADDRESS:localhost:9091}
          negotiation-type: PLAINTEXT
        category-service:
          address: ${CATEGORY_SERVICE_ADDRESS:localhost:9092}
          negotiation-type: PLAINTEXT



