services:
  order_service:
    build: .
    ports:
      - "${GRPC_PORT:-9094}:{GRPC_PORT:-9094}"
    environment:
      DATABASE_URI: ${DOCKER_DATABASE_URI}
    depends_on:
      - mongo-db
    profiles:
      - with-backend

  mongo_db:
    image: mongo:latest
    volumes:
      - dbdata6:/data/db
    ports:
      - "27020:27017"

volumes:
  db-data: