spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://localhost:27019/category}
  grpc:
    server:
      port: ${GRPC_PORT:9092}
    client:
      channels:
        product_service:
          address: ${PRODUCT_SERVICE_URL:localhost:9091}
          negotiation-type: PLAINTEXT


