
spring:
  application:
    name: "product-service"
  grpc:
    server:
      port: ${PORT:9091}


  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://localhost:27018/product}

  graphql:
    graphiql:
      enabled: true



#logging:
#  level:
#    org.springframework.grpc: DEBUG
#    io.grpc: DEBUG
