
spring:
  application:
    name: "product-service"

  grpc:
    server:
      port: ${GRPC_PORT:9091}


  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://localhost:27018/product}


#logging:
#  level:
#    org.springframework.grpc: DEBUG
#    io.grpc: DEBUG
