spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://localhost:27021/inventory}
  grpc:
    client:
      channels:
        product_service:
          address: ${PRODUCT_SERVICE_URL:localhost:9091}
          negotiation-type: PLAINTEXT
          secure: false
    server:
      port: ${GRPC_PORT:9095}
  kafka:
    bootstrap-servers: localhost:9097

