
services:
  inventory_service:
    build: .
    ports:
      - "${GRPC_PORT:-9095}:{GRPC_PORT:-9095}"
    environment:
      DATABASE_URI: ${DOCKER_DATABASE_URL}
    depends_on:
      - mongo_db
    profiles:
      - with_backend

  mongo_db:
    image: mongo:latest
    volumes:
      - dbdata6:/data/db
    ports:
      - "27021:27017"

volumes:
  dbdata6: